### ISSUE TITLE
file open but not closed 

### ISSUE THREAD

**Issue by allan-simon** [bluepeppers/libsg#1]
https://github.com/bluepeppers/libsg/blob/master/c/sgfile.c#L180

you do a fopen but you don't close it

**Comment by lclarkmichalek** [comment]
Merged jermenkoo's PR, let me know if it doesn't fix it. Out of interest, are you using this library in a project currently?

**Comment by allan-simon** [comment]
I'm re-playing Pharaoh recently on wine and by googling is there was some open source reimplementation of the game, I found there's some start of it, but nothing big.  And from link to link I've found your library , and I'm doing a implementation of it in Rust , we'll see where it goes  but at least it is keeping busy while commutating :P
